#!/usr/bin/env ruby -w

=begin

Problem 045 ()



---

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle      Tn = n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal    Pn = n(3n1)/2   1, 5, 12, 22, 35, ...
Hexagonal     Hn = n(2n1)   1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

---

Answer:

[1, 40755, 1533776805]

Took: 3.639591 secs.

2012-05-13

=end

t = Time.now


class Integer

  def triangle_num
    return self * (self + 1) / 2
  end

  def pentagonal_num
    return self * ((3 * self) - 1) / 2
  end

  def hexagonal_num
    return self * ((2 * self) - 1)
  end

end


LIMIT = 10**6

trig = Array.new
pent = Array.new
hexa = Array.new

(1..LIMIT).each do |n|
  trig << n.triangle_num
  pent << n.pentagonal_num
  hexa << n.hexagonal_num
end

puts (trig & pent & hexa).inspect

puts "\nTook: #{(Time.now - t)} secs."
