#!/usr/bin/env ruby -w
# -*- coding: utf-8 -*-

=begin

Problem 029 (25 October 2002)

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

---

Consider all integer combinations of ab for 2 <=  a <=  5 and 2 <=  b <=  5:
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 <=  a <= 100 and 2 <=  b <= 100?

---

Answer:

9183

Took: 0.175916086 secs.

2012-05-12

=end

t = Time.now

LOWER = 2
UPPER = 100

result = Array.new

(LOWER..UPPER).each do |a|
  (LOWER..UPPER).each do |b|
    result << a ** b
  end
end

puts result.uniq.sort.count

puts "\nTook: #{(Time.now - t)} secs."
